CREATE TABLE `llx_cfdimx_recepcion_pagos` (
  `rowid` int(11) NOT NULL AUTO_INCREMENT,
  `fk_facture` int(11) DEFAULT '0',
  `fk_paiement` int(11) DEFAULT '0',
  `fechaPago` varchar (50),
  `formaDePago` varchar(10) DEFAULT NULL,
  `monedaP` varchar(10) DEFAULT NULL,
  `TipoCambioP` double DEFAULT NULL,
  `monto` double DEFAULT NULL,
  `numOperacion` varchar(100) DEFAULT NULL,
  `rfcEmisorCtaOrd` varchar(50) DEFAULT NULL,
  `nomBancoOrdExt` text,
  `ctaOrdenante` varchar(50) DEFAULT NULL,
  `rfcEmisorCtaBen` varchar(50) DEFAULT NULL,
  `ctaBeneficiario` varchar(50) DEFAULT NULL,
  `tipoCadPago` varchar(255) DEFAULT NULL,
  `certPago` text,
  `cadPago` text,
  `selloPago` text,
  `xml` text,
  `cadena` text,
  `version` varchar (10) DEFAULT NULL, 
  `selloCFD` text,
  `certificado` varchar (250) DEFAULT NULL, 
  `sello` text, 
  `certEmisor` varchar (250) DEFAULT NULL, 
  `cancelado` integer (11) DEFAULT 0,   
  `uuid` varchar (250),
  `fecha_emision` date, 
  `hora_emision` time,
  `entity` int(11) DEFAULT NULL,
  PRIMARY KEY (`rowid`)
);