CREATE TABLE `llx_cfdimx_nomina` (
  `rowid` int(11) NOT NULL AUTO_INCREMENT,
  `tipo_timbrado` int(11) DEFAULT NULL,
  `factura_serie` varchar(50) DEFAULT NULL,
  `factura_folio` int(11) DEFAULT NULL,
  `factura_seriefolio` varchar(50) DEFAULT NULL,
  `xml` text,
  `cadena` text,
  `version` varchar(10) DEFAULT NULL,
  `selloCFD` text,
  `fechaTimbrado` varchar(50) DEFAULT NULL,
  `uuid` varchar(250) DEFAULT NULL,
  `certificado` varchar(250) DEFAULT NULL,
  `sello` text,
  `certEmisor` varchar(250) DEFAULT NULL,
  `cancelado` int(11) DEFAULT '0',
  `u4dig` int(11) DEFAULT NULL,
  `fk_salario` varchar(50) DEFAULT NULL,
  `fecha_emision` date DEFAULT NULL,
  `hora_emision` time DEFAULT NULL,
  `fecha_timbrado` date DEFAULT NULL,
  `hora_timbrado` time DEFAULT NULL,
  `divisa` varchar(4) DEFAULT NULL,
  `entity_id` int(11) DEFAULT NULL,
  `filetxt` varchar(255) DEFAULT NULL,
  PRIMARY KEY (`rowid`)
);